# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16e4bab73dbc933ac0a0c75c5b91de64eb7e72eef1d163ad32757f0c2c5f928c52f0e232b863cbd5db57617714b46b4b02d7948b988f841ad7cb639270417cdd

test:
  secret_key_base: 2693e96631fb46f26903e4e42ea2e5b37a00ec9ccc78da429e59f60a07a77b29c50c7dc5f0b13a0689711dbda7d33a850e113d48d64fa82b965d414dd3142911

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
